"""empty message

Revision ID: 27b0f97e8a3b
Revises: 5b30ca8b858d
Create Date: 2025-09-19 23:58:31.677950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b0f97e8a3b'
down_revision = '5b30ca8b858d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amendementen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=200), nullable=False),
    sa.Column('constaterende_dat', sa.Text(), nullable=True),
    sa.Column('overwegende_dat', sa.Text(), nullable=True),
    sa.Column('opdracht_formulering', sa.Text(), nullable=False),
    sa.Column('wijzigingen', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('gemeenteraad_datum', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amendementen')
    # ### end Alembic commands ###
