"""add motie_medeindieners m2m

Revision ID: 2c475353cb92
Revises: 46e872738514
Create Date: 2025-09-23 22:06:38.853811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c475353cb92'
down_revision = '46e872738514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motie_medeindieners',
    sa.Column('motie_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['motie_id'], ['motie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('motie_id', 'user_id'),
    sa.UniqueConstraint('motie_id', 'user_id', name='uq_motie_user')
    )
    op.drop_table('motie_partijen')
    with op.batch_alter_table('motie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indiener_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['indiener_id'], ['id'])
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
        batch_op.drop_column('indiener_id')

    op.create_table('motie_partijen',
    sa.Column('motie_id', sa.INTEGER(), nullable=False),
    sa.Column('partij_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['motie_id'], ['motie.id'], ),
    sa.ForeignKeyConstraint(['partij_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('motie_id', 'partij_id')
    )
    op.drop_table('motie_medeindieners')
    # ### end Alembic commands ###
