"""Initial migration

Revision ID: 3791f26e4a9d
Revises: 
Create Date: 2025-09-18 20:36:36.147851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3791f26e4a9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=100), nullable=False),
    sa.Column('afkorting', sa.String(length=10), nullable=False),
    sa.Column('kleur', sa.String(length=7), nullable=True),
    sa.Column('actief', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('afkorting'),
    sa.UniqueConstraint('naam')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('naam', sa.String(length=100), nullable=False),
    sa.Column('partij_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partij_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('motie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=200), nullable=False),
    sa.Column('constaterende_dat', sa.Text(), nullable=False),
    sa.Column('overwegende_dat', sa.Text(), nullable=False),
    sa.Column('draagt_college_op', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motie_partijen',
    sa.Column('motie_id', sa.Integer(), nullable=False),
    sa.Column('partij_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['motie_id'], ['motie.id'], ),
    sa.ForeignKeyConstraint(['partij_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('motie_id', 'partij_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motie_partijen')
    op.drop_table('motie')
    op.drop_table('user')
    op.drop_table('party')
    # ### end Alembic commands ###
