"""empty message

Revision ID: 4b9f217317aa
Revises: 5a22720e87e7
Create Date: 2025-09-19 11:08:52.780185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9f217317aa'
down_revision = '5a22720e87e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motie_partijen')
    with op.batch_alter_table('motie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opdracht_formulering', sa.Text(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('partij_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partij_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'party', ['partij_id'], ['id'])

    with op.batch_alter_table('motie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
        batch_op.drop_column('opdracht_formulering')

    op.create_table('motie_partijen',
    sa.Column('motie_id', sa.INTEGER(), nullable=False),
    sa.Column('partij_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['motie_id'], ['motie.id'], ),
    sa.ForeignKeyConstraint(['partij_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('motie_id', 'partij_id')
    )
    # ### end Alembic commands ###
