"""empty message

Revision ID: aa6d5689cec3
Revises: 3d4ef663f964
Create Date: 2025-09-24 09:28:09.209096

"""
from alembic import op
import sqlalchemy as sa, inspect


# revision identifiers, used by Alembic.
revision = 'aa6d5689cec3'
down_revision = '3d4ef663f964'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amendementen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indiener_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('created_by', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['indiener_id'], ['id'])
        batch_op.drop_column('created_by')

    with op.batch_alter_table('motie', schema=None) as batch_op:
        batch_op.alter_column('indiener_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('Field13')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Field13', sa.INTEGER(), nullable=True))
        batch_op.alter_column('indiener_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('amendementen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
        batch_op.drop_column('indiener_id')

    # ### end Alembic commands ###
