"""empty message

Revision ID: b4765fb9741f
Revises: 3791f26e4a9d
Create Date: 2025-09-23 22:29:51.628818

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b4765fb9741f'
down_revision = '3791f26e4a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    pass
