"""empty message

Revision ID: c58c98032ca9
Revises: e6002a28f3df
Create Date: 2025-09-19 19:51:00.771799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c58c98032ca9'
down_revision = 'e6002a28f3df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gemeenteraad_datum', sa.String(length=20), nullable=True))
        batch_op.alter_column('constaterende_dat',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('overwegende_dat',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('draagt_college_op',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motie', schema=None) as batch_op:
        batch_op.alter_column('draagt_college_op',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('overwegende_dat',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('constaterende_dat',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('gemeenteraad_datum')

    # ### end Alembic commands ###
