"""Added column for draagt college op'


Revision ID: ca19388fa969
Revises: 3791f26e4a9d
Create Date: 2025-09-18 21:16:17.733467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca19388fa969'
down_revision = '3791f26e4a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opdracht_formulering', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motie', schema=None) as batch_op:
        batch_op.drop_column('opdracht_formulering')

    # ### end Alembic commands ###
