"""empty message

Revision ID: e6002a28f3df
Revises: 4b9f217317aa
Create Date: 2025-09-19 11:12:19.946637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6002a28f3df'
down_revision = '4b9f217317aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motie_partijen',
    sa.Column('motie_id', sa.Integer(), nullable=False),
    sa.Column('partij_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['motie_id'], ['motie.id'], ),
    sa.ForeignKeyConstraint(['partij_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('motie_id', 'partij_id')
    )
    with op.batch_alter_table('motie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opdracht_formulering', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motie', schema=None) as batch_op:
        batch_op.drop_column('opdracht_formulering')

    op.drop_table('motie_partijen')
    # ### end Alembic commands ###
