"""empty message

Revision ID: f7f0e9034701
Revises: d89bb917805e
Create Date: 2025-09-20 10:44:56.007179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f0e9034701'
down_revision = 'd89bb917805e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('logo_filename', sa.String(length=255), nullable=True))
        batch_op.drop_column('kleur')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kleur', sa.VARCHAR(length=7), nullable=True))
        batch_op.drop_column('logo_filename')
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
