"""empty message

Revision ID: 46e872738514
Revises: d3e0b3a26e66
Create Date: 2025-09-23 21:20:29.593119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e872738514'
down_revision = 'd3e0b3a26e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('profile_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_filename')
        batch_op.drop_column('profile_url')

    # ### end Alembic commands ###
