"""empty message

Revision ID: 5b30ca8b858d
Revises: c58c98032ca9
Create Date: 2025-09-19 19:51:48.537633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b30ca8b858d'
down_revision = 'c58c98032ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motie', schema=None) as batch_op:
        batch_op.alter_column('gemeenteraad_datum',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motie', schema=None) as batch_op:
        batch_op.alter_column('gemeenteraad_datum',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
