"""empty message

Revision ID: 91403d2ba1f7
Revises: f7f0e9034701
Create Date: 2025-09-23 18:07:16.047739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91403d2ba1f7'
down_revision = 'f7f0e9034701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
