"""empty message

Revision ID: d89bb917805e
Revises: 27b0f97e8a3b
Create Date: 2025-09-20 00:01:53.179783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89bb917805e'
down_revision = '27b0f97e8a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amendementen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agendapunt', sa.String(length=40), nullable=True))

    with op.batch_alter_table('motie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agendapunt', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motie', schema=None) as batch_op:
        batch_op.drop_column('agendapunt')

    with op.batch_alter_table('amendementen', schema=None) as batch_op:
        batch_op.drop_column('agendapunt')

    # ### end Alembic commands ###
