"""empty message

Revision ID: e61986b7639b
Revises: 5075b53b4681
Create Date: 2025-09-26 15:56:24.128357

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e61986b7639b'
down_revision = '5075b53b4681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('motie_id', sa.Integer(), nullable=True),
    sa.Column('share_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['motie_id'], ['motie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_id'], ['motie_share.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_motie_id'), ['motie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_share_id'), ['share_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.drop_table('amendementen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amendementen',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titel', sa.VARCHAR(length=200), nullable=False),
    sa.Column('constaterende_dat', sa.TEXT(), nullable=True),
    sa.Column('overwegende_dat', sa.TEXT(), nullable=True),
    sa.Column('opdracht_formulering', sa.TEXT(), nullable=False),
    sa.Column('wijzigingen', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('gemeenteraad_datum', sa.VARCHAR(length=40), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('agendapunt', sa.VARCHAR(length=40), nullable=True),
    sa.Column('indiener_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['indiener_id'], ['user.id'], name=op.f('fk_amendementen_indiener_id_user_id')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_share_id'))
        batch_op.drop_index(batch_op.f('ix_notification_motie_id'))

    op.drop_table('notification')
    with op.batch_alter_table('motie_share', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_motie_share_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_motie_share_target_party_id'))
        batch_op.drop_index(batch_op.f('ix_motie_share_motie_id'))
        batch_op.drop_index(batch_op.f('ix_motie_share_created_by_id'))

    op.drop_table('motie_share')
    # ### end Alembic commands ###
